# -*- coding: utf-8 -*-
{
    'name': "Commission",
    'version' : '0.3',
    'summary': """Employee configuration is done through this module""",
    'sequence': 4,
    'icon': '/employee_commision/static/src/img/icon.png',
    'description': """Employee configuration is done through this module""",
    'author': "PMCS, @soyeb",
    'website': "http://int.primeminds.co/",
    'depends': ['base', 'hr', 'stock', 'point_of_sale', 'pos_salesperson', 'hr_payroll', 'product'],
    'data': [
        'security/ir.model.access.csv',
        'views/Employee_configuration.xml',
        'views/employee_commission.xml',
        'views/product_product_inherit.xml',
        'wizard/commission_computation_wizard.xml',
        'wizard/commission_slip_print.xml',
        'report/report.xml',
        'report/template.xml',
    ],
    'demo': [],
    'auto_install': False,
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}