{
    'name': 'User From Employee',
    'version': '15.0.0.3 15-mar',
    'summary': 'This module allows to creates User while creating Employee',
    'description': 'This module helps you to create user from employees',
    'category': 'Human Resources',
    'author': 'Prime Minds',
    'website': "https://primeminds.co/",
    'depends': ['base', 'hr'],
    'data': ['views/user_creation_from_employees_view.xml'],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
